version: '3.4'

services:
  todoapp.api:
    image: ${DOCKER_REGISTRY-}todoappapi
    build:
      context: .
      dockerfile: TodoApp.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
        - todoapp.database
  todoapp.ui:
    image: ${DOCKER_REGISTRY-}todoappui
    build:
      context: .
      dockerfile: TodoApp.UI/Dockerfile
    ports:
        - "5002:5002"
        - "5003:5003"
    depends_on:
        - todoapp.api
  todoapp.database:
    image: postgres:latest
    container_name: todoapp.database
    environment:
        - POSTGRES_MULTIPLE_DATABASES:"todoapp, sonarqube"
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - todoapp_db:/var/lib/postgresql/data
    ports:
        - 5432:5432  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: adnand.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    depends_on:
        - todoapp.database
    environment:
        - SONARQUBE_JDBC_USERNAME=postgres
        - SONARQUBE_JDBC_PASSWORD=postgres
        - SONARQUBE_JDBC_URL=jdbc:postgresql://todoapp.database:5432/sonarqube
    volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
        - 9000:9000
volumes:
  todoapp_db:
  pgadmin-data:
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:
